const s = {
  queryCost: 24,
  latitude: 28.6341,
  longitude: 77.2169,
  resolvedAddress: "Delhi, DL, India",
  address: "                      Delhi",
  timezone: "Asia/Kolkata",
  tzoffset: 5.5,
  days: [
    {
      datetime: "2024-10-11",
      datetimeEpoch: 1728585000,
      tempmax: 90.2,
      tempmin: 69.8,
      temp: 80.3,
      feelslikemax: 90.3,
      feelslikemin: 69.8,
      feelslike: 80.7,
      dew: 64.6,
      humidity: 61.6,
      precip: 0,
      precipprob: 0,
      precipcover: 0,
      preciptype: null,
      snow: 0,
      snowdepth: 0,
      windgust: 11.6,
      windspeed: 9.2,
      winddir: 275.3,
      pressure: 1010.3,
      cloudcover: 12.3,
      visibility: 2.3,
      solarradiation: 220.8,
      solarenergy: 19,
      uvindex: 8,
      severerisk: 10,
      sunrise: "06:19:42",
      sunriseEpoch: 1728607782,
      sunset: "17:55:35",
      sunsetEpoch: 1728649535,
      moonphase: 0.25,
      conditions: "Clear",
      description: "Clear conditions throughout the day.",
      icon: "clear-day",
      stations: [
        "42182099999",
        "42176099999",
        "VIDP",
        "42139099999",
        "42181099999",
      ],
      source: "obs",
      hours: [
        {
          datetime: "00:00:00",
          datetimeEpoch: 1728585000,
          temp: 78.8,
          feelslike: 78.8,
          humidity: 65.35,
          dew: 66.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11,
          windspeed: 2.2,
          winddir: 343.2,
          pressure: 1011,
          visibility: 2.5,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-night",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "01:00:00",
          datetimeEpoch: 1728588600,
          temp: 77,
          feelslike: 77,
          humidity: 69.35,
          dew: 66.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 8.5,
          windspeed: 3.4,
          winddir: 250,
          pressure: 1011,
          visibility: 2.5,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-night",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "02:00:00",
          datetimeEpoch: 1728592200,
          temp: 73.1,
          feelslike: 73.1,
          humidity: 81.24,
          dew: 67,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.8,
          windspeed: 1,
          winddir: 250,
          pressure: 1009.1,
          visibility: 1.4,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-night",
          stations: ["42182099999", "VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "03:00:00",
          datetimeEpoch: 1728595800,
          temp: 73.4,
          feelslike: 73.4,
          humidity: 83.22,
          dew: 68,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 6.3,
          windspeed: 3.4,
          winddir: 200,
          pressure: 1010,
          visibility: 1.9,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-night",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "04:00:00",
          datetimeEpoch: 1728599400,
          temp: 71.6,
          feelslike: 71.6,
          humidity: 88.44,
          dew: 68,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4.7,
          windspeed: 4.7,
          winddir: 220,
          pressure: 1010,
          visibility: 1.9,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-night",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "05:00:00",
          datetimeEpoch: 1728603000,
          temp: 70.2,
          feelslike: 70.2,
          humidity: 86.57,
          dew: 66,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 3.1,
          windspeed: 1.3,
          winddir: 250,
          pressure: 1009.8,
          visibility: 1.3,
          cloudcover: 0,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-night",
          stations: ["42182099999", "VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "06:00:00",
          datetimeEpoch: 1728606600,
          temp: 69.8,
          feelslike: 69.8,
          humidity: 88.35,
          dew: 66.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 2.7,
          windspeed: 3.4,
          winddir: 250,
          pressure: 1011,
          visibility: 1.9,
          cloudcover: 27.2,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "07:00:00",
          datetimeEpoch: 1728610200,
          temp: 71.6,
          feelslike: 71.6,
          humidity: 83.11,
          dew: 66.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 2.9,
          windspeed: 3.4,
          winddir: 220,
          pressure: 1012,
          visibility: 1.9,
          cloudcover: 27.2,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "08:00:00",
          datetimeEpoch: 1728613800,
          temp: 76,
          feelslike: 76,
          humidity: 72.72,
          dew: 66.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4.9,
          windspeed: 6.6,
          winddir: 252,
          pressure: 1011.1,
          visibility: 1.3,
          cloudcover: 29.2,
          solarradiation: 67,
          solarenergy: 0.2,
          uvindex: 1,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: [
            "42182099999",
            "42176099999",
            "VIDP",
            "42139099999",
            "42181099999",
          ],
          source: "obs",
        },
        {
          datetime: "09:00:00",
          datetimeEpoch: 1728617400,
          temp: 78.8,
          feelslike: 78.8,
          humidity: 65.35,
          dew: 66.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.4,
          windspeed: 6.9,
          winddir: 280,
          pressure: 1013,
          visibility: 1.9,
          cloudcover: 27.2,
          solarradiation: 259,
          solarenergy: 0.9,
          uvindex: 3,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "10:00:00",
          datetimeEpoch: 1728621000,
          temp: 82.4,
          feelslike: 84,
          humidity: 54.58,
          dew: 64.4,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 7.4,
          windspeed: 6.9,
          winddir: 290,
          pressure: 1013,
          visibility: 1.9,
          cloudcover: 0,
          solarradiation: 462,
          solarenergy: 1.7,
          uvindex: 5,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-day",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "11:00:00",
          datetimeEpoch: 1728624600,
          temp: 88.2,
          feelslike: 89.7,
          humidity: 45.45,
          dew: 64.4,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 8.1,
          windspeed: 9.1,
          winddir: 276,
          pressure: 1010.7,
          visibility: 2.3,
          cloudcover: 0,
          solarradiation: 630,
          solarenergy: 2.3,
          uvindex: 6,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-day",
          stations: ["42182099999", "VIDP", "42139099999", "42181099999"],
          source: "obs",
        },
        {
          datetime: "12:00:00",
          datetimeEpoch: 1728628200,
          temp: 89.6,
          feelslike: 90.3,
          humidity: 40.72,
          dew: 62.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 9.6,
          windspeed: 9.2,
          winddir: 300,
          pressure: 1011,
          visibility: 2.5,
          cloudcover: 0,
          solarradiation: 742,
          solarenergy: 2.7,
          uvindex: 7,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-day",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "13:00:00",
          datetimeEpoch: 1728631800,
          temp: 89.6,
          feelslike: 89.5,
          humidity: 38.21,
          dew: 60.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 10.5,
          windspeed: 8.1,
          winddir: 290,
          pressure: 1010,
          visibility: 2.5,
          cloudcover: 0,
          solarradiation: 787,
          solarenergy: 2.8,
          uvindex: 8,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-day",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "14:00:00",
          datetimeEpoch: 1728635400,
          temp: 90.2,
          feelslike: 90.1,
          humidity: 37.26,
          dew: 60.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11,
          windspeed: 6.6,
          winddir: 288,
          pressure: 1007.8,
          visibility: 2.6,
          cloudcover: 0,
          solarradiation: 760,
          solarenergy: 2.7,
          uvindex: 8,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-day",
          stations: ["42182099999", "VIDP", "42139099999", "42181099999"],
          source: "obs",
        },
        {
          datetime: "15:00:00",
          datetimeEpoch: 1728639000,
          temp: 89.6,
          feelslike: 88.9,
          humidity: 35.84,
          dew: 59,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.4,
          windspeed: 9.2,
          winddir: 270,
          pressure: 1009,
          visibility: 3.1,
          cloudcover: 0,
          solarradiation: 664,
          solarenergy: 2.4,
          uvindex: 7,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-day",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "16:00:00",
          datetimeEpoch: 1728642600,
          temp: 89.6,
          feelslike: 89.5,
          humidity: 38.21,
          dew: 60.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.6,
          windspeed: 8.1,
          winddir: 280,
          pressure: 1009,
          visibility: 3.1,
          cloudcover: 0,
          solarradiation: 508,
          solarenergy: 1.8,
          uvindex: 5,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-day",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "17:00:00",
          datetimeEpoch: 1728646200,
          temp: 87.7,
          feelslike: 89.7,
          humidity: 47.52,
          dew: 65.3,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.6,
          windspeed: 4.7,
          winddir: 276,
          pressure: 1007.6,
          visibility: 2.6,
          cloudcover: 27.2,
          solarradiation: 311,
          solarenergy: 1.1,
          uvindex: 3,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: [
            "42182099999",
            "42176099999",
            "VIDP",
            "42139099999",
            "42181099999",
          ],
          source: "obs",
        },
        {
          datetime: "18:00:00",
          datetimeEpoch: 1728649800,
          temp: 84.2,
          feelslike: 85,
          humidity: 48.35,
          dew: 62.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 11.4,
          windspeed: 3.4,
          winddir: 280,
          pressure: 1009,
          visibility: 3.1,
          cloudcover: 27.2,
          solarradiation: 109,
          solarenergy: 0.4,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "19:00:00",
          datetimeEpoch: 1728653400,
          temp: 84.2,
          feelslike: 85,
          humidity: 48.35,
          dew: 62.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 9.2,
          windspeed: 3.4,
          winddir: 280,
          pressure: 1010,
          visibility: 3.1,
          cloudcover: 27.2,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "20:00:00",
          datetimeEpoch: 1728657000,
          temp: 78.5,
          feelslike: 78.5,
          humidity: 69.5,
          dew: 67.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 6,
          windspeed: 1.3,
          winddir: 314,
          pressure: 1009.4,
          visibility: 2.5,
          cloudcover: 18.4,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Clear",
          icon: "clear-night",
          stations: ["42182099999", "VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "21:00:00",
          datetimeEpoch: 1728660600,
          temp: 80.6,
          feelslike: 82.3,
          humidity: 57.87,
          dew: 64.4,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 4.5,
          windspeed: 4.7,
          winddir: 300,
          pressure: 1011,
          visibility: 2.5,
          cloudcover: 27.2,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "22:00:00",
          datetimeEpoch: 1728664200,
          temp: 78.8,
          feelslike: 78.8,
          humidity: 57.63,
          dew: 62.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 6.3,
          windspeed: 2.2,
          winddir: 313.3,
          pressure: 1011,
          visibility: 2.5,
          cloudcover: 27.2,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: ["VIDP", "42181099999"],
          source: "obs",
        },
        {
          datetime: "23:00:00",
          datetimeEpoch: 1728667800,
          temp: 74.1,
          feelslike: 74.1,
          humidity: 75.05,
          dew: 65.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 0,
          preciptype: null,
          windgust: 10.5,
          windspeed: 0,
          winddir: 0,
          pressure: 1009.8,
          visibility: 2.5,
          cloudcover: 29.2,
          solarradiation: 0,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: ["42182099999", "VIDP", "42181099999"],
          source: "obs",
        },
      ],
    },
  ],
  stations: {
    42139099999: {
      distance: 64729,
      latitude: 29.017,
      longitude: 77.717,
      useCount: 0,
      id: "42139099999",
      name: "MEERUT, IN",
      quality: 58,
      contribution: 0,
    },
    42181099999: {
      distance: 13429,
      latitude: 28.567,
      longitude: 77.103,
      useCount: 0,
      id: "42181099999",
      name: "INDIRA GANDHI INTERNATIONAL, IN",
      quality: 99,
      contribution: 0,
    },
    42182099999: {
      distance: 5627,
      latitude: 28.585,
      longitude: 77.206,
      useCount: 0,
      id: "42182099999",
      name: "SAFDARJUNG, IN",
      quality: 69,
      contribution: 0,
    },
    42176099999: {
      distance: 65702,
      latitude: 28.833,
      longitude: 76.583,
      useCount: 0,
      id: "42176099999",
      name: "ROHTAK, IN",
      quality: 54,
      contribution: 0,
    },
    VIDP: {
      distance: 11858,
      latitude: 28.57,
      longitude: 77.12,
      useCount: 0,
      id: "VIDP",
      name: "VIDP",
      quality: 49,
      contribution: 0,
    },
  },
};

function getFormattedDate() {
  const date = new Date();

  const year = date.getFullYear();
  let month = date.getMonth();
  let day = date.getDate();

  if (month < 10) month = "0" + month;
  if (day < 10) day = "0" + day;

  const formattedDate = year + "-" + month + "-" + day;
  return formattedDate;
}

async function getWeatherDetails(location) {
  const apiKey = "BJCPFH9PN5H9AYVG9BKMZ34WH";
  const endPoint = `https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/
                      ${location}/${getFormattedDate()}?key=${apiKey}`;

  try {
    const response = await fetch(endPoint);
    // console.log(response);
    const json_response = await response.json();
    // console.log(json_response);
    return json_response;
  } catch (err) {
    console.log(err);
  }
}

export async function processData(location = "Delhi") {
  // const rawData = await getWeatherDetails(location)
  const rawData = s;

  let area = rawData["resolvedAddress"].split(",");
  area = area[0] + "," + area.at(-1);
  console.log(area);

  console.log(new Date().toLocaleString());

  const data = rawData["days"][0];
  const temp = data["temp"];
  console.log(temp);

  const condition = data["conditions"];
  console.log(condition);

  const feelsLike = data["feelslike"];
  console.log(feelsLike);

  const humidity = data["humidity"] + "%";
  console.log(humidity);

  const windspeed = data["windspeed"] + "km/hr";
  console.log(windspeed);

  return { area, temp, condition, feelsLike, humidity, windspeed };
}
